services:
  glass:
    build: .
    restart: always
    networks:
      - traefik
      - glass
    env_file:
      - src/.env
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.glass.rule=Host(`glass.localhost`)'
    depends_on:
      glass-db:
        condition: service_started
    volumes:
      - ./src:/var/www/html

  glass-db:
    image: 'mariadb:11.4.7'
    restart: always
    volumes:
      - glass-db:/var/lib/mysql
    environment:
      MARIADB_DATABASE: glass
      MARIADB_ROOT_PASSWORD: password
      MARIADB_USER: glass
      MARIADB_PASSWORD: password
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - glass

volumes:
  glass-db:
    name: glass-db

networks:
  traefik:
    external: true
  glass:
    name: glass
